### ISSUE TITLE
Add support for HTTP Accept header

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#101]
1. Add support for HTTP `Accept` header to specify content type.
2. Update `output` parameter to be optional

`Accept` header controls whether or not to include the metadata about the request/response in the response body.

If `Accept` header is not `text/csv` or `application/geo+json`, the `output` parameter is optional but will default to `geojson`. The response will be structured as:
```
{
    "status": "200 OK",
    "time": 458.179,
    "hits": 3,
    "results": {
        "csv": "",
        "geojson": {...}
    }
}
```

If `Accept` header is `application/geo+json`, the response will include only the value of the `geojson` attribute from the non-raw response. The `output` parameter should be omitted.

If `Accept` header is `text/csv`, the response will include only the value of the `csv` attribute from the non-raw response. The `output` parameter should be omitted.

Example if `Accept` header is `application/geo+json`:
```
{
            "type": "FeatureCollection",
            "features": [
                {
                    "id": "0",
                    "type": "Feature",
                    "properties": {
                        "reach_id": "73282400171",
                        "time_str": "2023-07-28T22:10:37Z",
                        "wse": "211.178",
                        "slope": "-0.0007516914999999999"
                    },
                    "geometry": {
                        "type": "LineString",
                        "coordinates": [...]
                    }
                },
                {
                    "id": "1",
                    "type": "Feature",
                    "properties": {
                        "reach_id": "73282400171",
                        "time_str": "2023-09-08T15:40:49Z",
                        "wse": "82.082",
                        "slope": "-1.0184e-06"
                    },
                    "geometry": {
                        "type": "LineString",
                        "coordinates": [...]
                    }
                },
                {
                    "id": "2",
                    "type": "Feature",
                    "properties": {
                        "reach_id": "73282400171",
                        "time_str": "2023-09-29T12:25:52Z",
                        "wse": "206.49349999999998",
                        "slope": "-0.0007833485000000001"
                    },
                    "geometry": {
                        "type": "LineString",
                        "coordinates": [...]
                    }
                }
            ]
        }
```

To summarize:

Value of `Accept` header:

- `text/csv` as first match in list: output is raw csv content 
- `application/geo+json` as first match in list: output is raw geojson content
- `application/json` as first match in list: output is json content
- wildcard that includes `application/json` (e.g. `image/webp,image/*,*/*;q=0.8`): output is json content because */* includes application/json (can use https://pypi.org/project/accept-types/ to help with this parsing)
- Other specific unsupported media type (e.g. `image/jpg`): 415 Unsupported Media Type

Supported media types:
https://www.iana.org/assignments/media-types/text/csv `text/csv`
https://www.iana.org/assignments/media-types/application/geo+json `application/geo+json`
https://www.iana.org/assignments/media-types/application/json `application/json`

**Comment by frankinspace** [comment]
A few different scenarios and how the API should behave:

- `Accept: application/geo+json`, `raw=true`: Return a valid GeoJSON FeatureCollection object
- `Accept: application/geo+json`, `raw=false`: 400 Bad Request - Invalid Accept header for non-raw responses. Remove the raw request parameter or use application/json as the Accepted content type.
- `Accept: text/csv`, `raw=true`: Return direct csv content
- `Accept: text/csv`, `raw=false`: 400 Bad Request - Invalid Accept header for non-raw responses. Remove the raw request parameter or use application/json as the Accepted content type with output request parameter set to csv.
- `Accept: application/json`, `raw=true`: Return a valid GeoJSON FeatureCollection object
- `Accept: application/json`, `raw=false`: Return a json object with status, time, hits, and results. Results should be geojson
- `Accept: application/json`, `raw=true`, `output=geojson`: Return a valid GeoJSON FeatureCollection object
- `Accept: application/json`, `raw=true`, `output=csv`: Return direct csv content
- `Accept: application/json`, `raw=false`, `output=csv`: Return a json object with status, time, hits, and results. Results should be csv
- `Accept: */*`: Return a json object with status, time, hits, and results. Results should be geojson

**Comment by nikki-t** [comment]
> * `Accept: text/csv,application/geo+json,application/json`, `output=csv`: Return direct csv content

Should this case also return a 400 Bad Request so that it is consistent with the example where the 'Accept' header is the same but the output is set to geojson?

**Comment by frankinspace** [comment]
Maybe we can have a discussion about these behaviors. I put this together but re-reading it I think there might be easier logic if we start with processing the output parameter first. Basically, if output parameter is provided; assume application/json response body; if application/json is not covered by the Accept header, then return the 400 error.

If output parameter is not provided; then just use the Accept header to determine the response body content. text/csv is direct csv content, application/geo+json is direct geojson, and application/json includes metadata with output defaulted to geojson format
