### ISSUE TITLE
Add SWORD version from shp.xml to DB entries

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#13]
Stakeholder requested returning the SWORD version from the SWOT shapefiles as a field with the data attributes. This info is in a separate xml file in the shp zip so requires a bit of special handling.

**Comment by torimcd** [comment]
Related to #24

**Comment by torimcd** [comment]
The <xref_prior_river_db_files> tag in the *.shp.xml files contains netcdf files for each swath generated from SWORD. These files follow the naming convention `SWOT_RiverDatabase_Nom_231_208L_20200101T000000_21000101T000000_20230414T153800_v215.nc` where the last two digits of the version tag `v215` indicate the version of SWORD that the SWATH files were derived from. We can parse these digits out of these filenames to input as a sword_version field in each record

**Comment by nikki-t** [comment]
Going to start work to add SWORD version to API response.
