### ISSUE TITLE
Feature Analysis: Add Lake data to Hydrocron

### ISSUE THREAD

**Issue by nikki-t** [podaac/hydrocron#133]
# Feature Analysis: Add Lake data to Hydrocron

## Overview

SWOT produces [Level 2 Lake Single-Pass Vector data](https://podaac.jpl.nasa.gov/dataset/SWOT_L2_HR_LakeSP_2.0) (L2_HR_LakeSP). This data is organized similary to the [Level 2 River Single-Pass Vector data](https://podaac.jpl.nasa.gov/dataset/SWOT_L2_HR_RiverSP_2.0) that is already present in Hydrocron. The L2_HR_LakeSP product provides lake data for each continent and is "...generally produced for inland and coastal hydrology surfaces" ([SWOT Product Description Document](https://deotb6e7tfubr.cloudfront.net/s3-edaf5da92e0ce48fb61175c28b67e95d/podaac-ops-cumulus-docs.s3.us-west-2.amazonaws.com/web-misc/swot_mission_docs/pdd/SWOT-TN-CDM-0673-CNES_Product_Description_L2_HR_LakeSP_20231208_RevB_signed.pdf?A-userid=None&Expires=1711648431&Signature=PDntR9xD26~GUVS0A9UB~MDfWhD35bHAWpZ0d7fo5TAhSaz3fHx7eFJg1fUbbLhGRfDWs~nispWehvyeAbiGhBoXgvDXy~vj8G-F~oxDICQfzgCXP9K9O4bvFSH5A13H9ftdQ9SxJ0XSrRmNSugbi2hPUQCTVLnRgPoRO~kImzfdg1xjJ3~kOGv9eah1JUl5~2ponqwV1WbVuTgv-zFvZl8IpmVrMKoHFfNCh3Evx49lWhfpQqxi6TyHq24Nkro6XfxjZpJ1OKK2SavKI4jg47w7SaGcGScyEgJQDVMF0kq5FhliGu9xJnh8ZTBHzkJ-FSSgr8uWr3LcEjVjHH0ImQ__&Key-Pair-Id=KZRIRLMTAHKYV)). 

Like the river data, the lake data is in shapefile format making time series aggregation difficult. Lake data users could greatly benefit from querying Hydrocron for time series lake data. Lake features and identifiers are taken from the Prior Lake Database (PLD).

A single lake granule consists of 3 shapefiles where each shapefile includes records of shape type polygon.

- an observation-oriented shapefile of lakes identified in the PLD
- a PLD-oriented shapefile of lakes identified in the PLD
- a shapefile of unassigned features (i.e., not identified in PLD nor PRD)

Each lake record is associated with a single time which is the average time of all measurements contributing to the record.

Attributes stored with lake shape data include

- observation identifier (obs_id)
- lake identifier (lake_id)
- water surface elevation (wse)
- water surface area (area_total)
- quality indicators
- storage change for PLD-oriented shapefile

## Use Cases

As a user, I want to retrieve lake data so that I can ...

## Acceptance Criteria (Requirements)

- The scope of the work to add lake data to Hydrocron has been understood and agreed upon.
- Lake data has been added to the Hydrocron database.
- Lake data has been added to the Hydrocron time series API endpoint.
- New log data that capture lake data operations and failures have been ingested into Cloud Metrics.
- The new lake operations have been tested in SIT.
- The new lake operations have been deployed to and tested in UAT.
- Feedback has been incorporated from UAT testing.
- A delivery memo, deploymment plan, and operational readiness review have been completed.
- The lake data operations have been deployed to OPS.

## High-Level Arhictecture

A diagram and text overview of the top-level architecture goes here.

## Challenges & Risks

List of various challenges and risks go here.

**Comment by nikki-t** [comment]
Here is a draft of the feature analysis we would like to complete for adding lake data to Hydrocron. I have filled out a little bit but need help really understanding both the use cases as well as the requirements so that we can come up with a potential architecture. I think we can cover this during our bi-weekly Hydrocron tag ups and capture progress here.

**Comment by cassienickles** [comment]
Lakes Use Cases Document: https://docs.google.com/document/d/1m9C-Fyy0Otar4eat28IHxbZtKIFtYshWGnFXYHHOgAE/edit?pli=1

**Comment by Ryan-Riggs** [comment]
I'm excited about this addition as it would significantly improve our ability to run the LakeFlow algorithm locally. LakeFlow uses SWOT observations of both lakes and rivers to estimate discharge at lake inflows and outflows.
