### ISSUE TITLE
Modify the GitHub Actions workflow for UAT deployments

### ISSUE THREAD

**Issue by nikki-t** [podaac/hydrocron#145]
The GitHub Actions workflow currently does not bump to the correct version for UAT deployments and can only be triggered manually.

Two solutions could be:
1. Update [build.yml](https://github.com/podaac/hydrocron/blob/develop/.github/workflows/build.yml) logic to bump the rc version if the it is the first build of a release branch. (More complicated).
2. Update [build.yml](https://github.com/podaac/hydrocron/blob/develop/.github/workflows/build.yml) to trigger on create events filtered to the release branches. (Less complicated and preferred).

**Comment by frankinspace** [comment]
Think this got fixed during 1.1.0 release, will use 1.2.0 release to verify

**Comment by nikki-t** [comment]
Can confirm that this was fixed. 1.2.0 release was deployed and the correct version was tagged for the deployment: `1.2.0rc1`. And the GitHub Actions workflows (Build and Release Branch) were triggered by the push of `release/1.2.0` to GitHub repo.

The develop branch was also tagged correctly: `1.3.0a0`.
