### ISSUE TITLE
returns goemetry even if not requested in fields parameter

### ISSUE THREAD

**Issue by devincowan** [podaac/hydrocron#154]
When making a request to Hydrocron using `output='geojson'`, the geometry is always included even if the request `fields` didn't specify it.

Example with `fields=time_str,wse,slope`:
https://localhost/api/hydrocron/v1/timeseries?feature=Reach&feature_id=13351000375&start_time=2024-01-01T00%3A00%3A00Z&end_time=2024-10-30T00%3A00%3A00Z&output=geojson&fields=time_str%2Cwse%2Cslope

See that geometry is still returned:
![image](https://github.com/podaac/hydrocron/assets/17934193/09937977-def9-4899-a5be-ff3693ed0ee8)

It would be nice if we could decrease latency by having the option not to include the geometry.

**Comment by nikki-t** [comment]
This is a great point and I think we have captured some of it in Issue #100 but feel free to provide further feedback!

Our thinking was that we would want to return valid GeoJSON for the GeoJSON output which I believe requires a geometry for Feature objects but we could then create a separate API option to return a single Feature where the `properties` object includes all values for the `fields` requested. I bet we could work out the exclusion of geometry from that object if it is not listed in the request fields.

**Comment by devincowan** [comment]
Makes sense thanks all, I'll close this issue in favor of #100
