### ISSUE TITLE
Use "range_start_time" for time in queries

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#16]
Update the API to use the continent cycle/pass "range_start_time" as the time field for queries. This will handle the issue of fillvalues and no_data values in the observed time and time_str fields in the shapefiles. 

Database code already adds the range_start_time field from the filenames as a field on each item when adding to the database.

**Comment by frankinspace** [comment]
@torimcd @vggonzal Is this still relevant?

**Comment by torimcd** [comment]
This is a duplicate of #42
