### ISSUE TITLE
Drop UAT tables and reload data

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#163]
Required due to issues discussed in https://github.com/podaac/hydrocron/issues/161

**Comment by frankinspace** [comment]
Need an AWS CLI command to kick off the lambda so that it can be scripted to run 4 days at a time

**Comment by ymchenjpl** [comment]
4/23/24 - Deleted the 2 tables in Services UAT and ran the load-data Lambda for the Reach table per UAT wiki page:
https://wiki.jpl.nasa.gov/display/PD/Hydrocron+v1.2.0+User+Scenarios+-+Internal+UAT+in+Services+UAT+-+04-23-2024
Only needed to load Jan & Feb 2024 data into Services UAT per Victoria.
The load-data for the Node table will be started on 4/24/24.

**Comment by ymchenjpl** [comment]
4/25/24 - Completed successful dry-run of script to load-data for Node table for Jan & Feb 2024 into Services UAT.
Also ran the load-benchmarking command in Services UAT
