### ISSUE TITLE
Load real data in OPS DB

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#164]
Plan at the moment is to wait for 1.2.0 release, then execute #163 , then run in OPS

**Comment by ymchenjpl** [comment]
After successful dry-run in Services UAT, Ying prepared OPS deployment wiki page for Hydrodron v1.2.0 Load Data at: https://wiki.jpl.nasa.gov/display/PD/Hydrocron+v1.2.0+OPS+Services+Deployment+Procedure+-+04-30-2024
Will wait for ORR go-ahead before proceeding.

**Comment by ymchenjpl** [comment]
After Frank deployed Hydrocron v1.2.0 to Services OPS on 4/30/24, Tim and Max ran the load-data lambda scripts to populate the Reach and Node tables per 
https://wiki.jpl.nasa.gov/display/PD/Hydrocron+v1.2.0+OPS+Services+Deployment+Procedure+-+04-30-2024

And then will run Benchmarking command.

Last step is to get instructions on how to turn on forward-stream ingest.
