### ISSUE TITLE
Load historical prior lake data into hydrocron

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#195]
Depends on:
https://github.com/podaac/hydrocron/issues/193

May want to do prior to:
https://github.com/podaac/hydrocron/issues/194

Depending on timing, may not need historical if we choose to only process the new collection which will start reprocessing/forward in October.

Need to execute script which will run load data lambda for historical granules.

**Comment by torimcd** [comment]
This is blocked by #210

**Comment by ymchenjpl** [comment]
10/15/24 - Ying created Run script and Tim used it to finish the bulk-loading of the historical granules for the SWOT_L2_HR_LakesSP_2.0 collection into the new Hydrocron SWOT prior lakes DynamoDB table per:
https://wiki.jpl.nasa.gov/display/PD/Hydrocron+v1.4.0+OPS+Services+Deployment+Procedure+-+2024-09-30
