### ISSUE TITLE
Cost model impact for new prior lake database table

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#197]
- Determine storage estimates for new data and inform @jimmie

**Comment by torimcd** [comment]
compare to the reach & node table size

**Comment by torimcd** [comment]
Expected capacity for each of the individual lake products (prior, observed, unassigned) is approx 1.7 million records/day (mean estimate), which corresponds to ~90 GB/month, ~1 TB/year per subcollection.
