### ISSUE TITLE
Implement queries for cmr and hydrocron

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#198]
- refine https://github.com/podaac/hydrocron/blob/feature/issue-71/hydrocron/db/track_status.py prototype for cmr query
- add new query to https://github.com/podaac/hydrocron/blob/develop/hydrocron/api/data_access/db.py for hydrocron query
- may need placeholder for start date

**Comment by nikki-t** [comment]
We will de-scope determining overlap and what exists in Hydrocron but not CMR for now. Create #206 to track future work.
