### ISSUE TITLE
(Optional) add checksum during forward processing ingest

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#200]
- Get checksum for file from initial CNM message and store it in the ingest status tracking table

**Comment by nikki-t** [comment]
The cnm_handler Lambda function should be modified to pass `revision_date` and `checksum` to the `granule_handler` Lambda function. This function can then add the granule to the track ingest database making sure to add a status of "to_ingest" for any granules that could not be ingested. If successful no status attribute is needed. The `feature_count` attribute can be set to 0 as this will trigger the submission of the granule for ingestion to Hydrocron by the track ingest program.

See #201 for context as this supports the current table schema and ensures we don't miss any granules.

**Comment by nikki-t** [comment]
Checksum is stored in the track ingest table by the load granule Lambda function as captured in #222.
