### ISSUE TITLE
Create table for tracking granule ingest status

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#201]
- Determine table name
- Write terraform script that will setup the table and permissions to the table
- enable PITR

**Comment by nikki-t** [comment]
Just want to document some decisions and solicit any feedback.

The track status table has the following attributes: `granuleUR`, `revision_date`, `feature_count`, `checksum`, `status`

The table has a hash key of `granuleUR` and a range key of `revision_date` to allow searching by granule.

The table also has a global secondary index (GSI) that supports a [sparse index](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general-sparse-indexes.html) to support querying over a small subset of the table. The GSI has a hash key of status which is only present to indicate that a granule has been submitted for ingest and requires checking during the next execution of the track ingest program to make sure the granule ingestion was successful. When this occurs, the status attribute is set to "to_ingest". This allows the track ingest program to query for all granules with a status of "to_ingest".

The `cnm_handler` Lambda function should be modified to pass `revision_date` and `checksum` to the `granule_handler` Lambda function. This function can then add the granule to the track ingest database making sure to add a status of "to_ingest" for any granules that could not be ingested. If successful no status attribute is needed. The `feature_count` attribute can be set to 0 as this will trigger the submission of the granule for ingestion to Hydrocron by the track ingest program.

However if we get a lot of granules with the "to_ingest" status we may run into [data partitioning issues](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-uniform-load.html) and may want to rethink our architecture. The idea was that we would only have a small subset of the granules marked with a status and therefore it would take up a relatively small amount of storage as a partition and allow for faster queries.

I have tested this by querying CMR and adding items to a local DynamoDB instance with the table structured implemented as above and it works well for querying on a subset of the granules.

I think we may also be able to set the read and write capacity units on the GSI based on perceived retrievals.
