### ISSUE TITLE
Determine overlap of data in cmr and data in hydrocron

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#202]
- Compare contents of CMR to what has been ingested into hydrocron
- Data not in CMR will trigger hydrocron ingest
- track status table updated to indicate data will be ingested
- ?? Log statement if data exists in hydrocron and not CMR

**Comment by nikki-t** [comment]
Closing as not implementing for now due to complexity of changing table structure or defining new table operations. See: https://github.com/podaac/hydrocron/issues/198#issuecomment-2236816122
