### ISSUE TITLE
Cost model impact for new track status database table

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#204]
- Determine storage estimates for new data and inform @jimmie

**Comment by nikki-t** [comment]
Looking at the product data descriptions for [Rivers](https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-docs/web-misc/swot_mission_docs/pdd/D-56413_SWOT_Product_Description_L2_HR_RiverSP_20231026_RevBcite.pdf) and [Lakes](https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-docs/web-misc/swot_mission_docs/pdd/SWOT-TN-CDM-0673-CNES_Product_Description_L2_HR_LakeSP_20231208_RevB_signed.pdf), I came up with the following estimates:

| feature type | daily granules | average item size | daily size | yearly size |
|-------------|--------------------|-------------------|----------|------------|
|reach | 65 | 227.92 bytes | 14.81 KB | 5.407 MB |
|node | 65 | 222.42 bytes | 14.46 KB | 5.278 MB |
|prior lake | 59 | 202.44 bytes | 11.94 KB | 4.36 MB |
|totals | 189 | 217.59 bytes (avg) | 41.21 KB | 15.045 MB |

The daily granule numbers were a best guess taken from Earthdata search. The volume will grow each year we accumulate SWOT granules but the actual size of the track ingest records are very small.
