### ISSUE TITLE
Track ingest table can be populated with granules that aren't loaded into Hydrocron

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#235]
The load granule module can add entries for granules that are not loaded into Hydrocron. For example, we only have tables for the prior lakes. If an observed lake granule is manually sent to the load_granule lambda, it will fail to load into the hydrocron tables but it will load the granule into the track table specified in the lambda event, regardless of feature type. 

This is not critical for the 1.4.0 release because the track ingest feature is not complete, and you can tell which entries are affected by granuleUR and the expected feature count will be zero. This also shouldn't happen in OPS since the load_granule lambda is only ever run via the CNM lambda or the bulk load_data lambda which both handle this edge case correctly. But we'll need to fix this and clear out bad entries that end up in SIT & UAT prior to the next release.

**Comment by frankinspace** [comment]
Seems like this is a low likelihood and low impact if it were to happen. @nikki-t will check with @torimcd on details.

**Comment by nikki-t** [comment]
It is also possible to enter a collection short name that doesn't match the corresponding Hydrocron SWOT table name or Hydrocron track ingest table name as in:

```
  "collection_shortname": "SWOT_L2_HR_RiverSP_reach_2.0",
  "hydrocron_table": "hydrocron-swot-node-table",
  "hydrocron_track_table": "hydrocron-swot-node-track-ingest-table",
```

where the reach shortname is entered while the node-level tables are entered.

We should place conditional statements in the track ingest Lambda code to test that the "event" arguments align.
