### ISSUE TITLE
Handle overlapping times with unique CRIDS

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#250]
Within the same collection version there are multiple granules for the same cycle/pass but with different CRIDs. This happens when there is a period of overlap between forward processing and reprocessing. For the SWOT_L2_HR_RiverSP_2.0 collection, there are duplicate granules from ~2023/11/21 (when CRID=PIC0 started in forward stream) to ~2024/01/25 (the end of the timeframe covered in the first reprocessing, with products having CRID=PGC0).

Hydrocron's database uses reach_id/range_start_time as the primary key - so if an overlapping granule is ingested, the data for that reach_id/time will be overwritten with the latest ingested granule. This is the correct behavior, we want the latest CRIDs to be the data we're exposing. 

For the track ingest feature, this means that granules with the earlier CRID will no longer be present in the Hydrocron db, so if we are automatically retrying/ingesting granules that are identified as missing from hydrocron, we risk overwriting the later CRIDS with with the earlier CRIDs. We should implement a check to be sure we're not overwriting the latest most accurate data with an earlier version.

**Comment by nikki-t** [comment]
The track ingest Lambda performs the following operations:

1. Query CMR and Hydrocron for granules and determine what has not been ingested (this is what is CMR but not in Hydrocron).
2. Query the track ingest table for granules with a "to_ingest" status to verify that granules have been ingested (this is done by counting the number of features associated with a specific `granuleUR` in the Hydrocron SWOT table).
3.  Construct and send CNM to trigger load data for granules that were not ingested.
4. Update track ingest table with new granules statuses (removes "to_ingest" for granules where expected feature count equals actual feature count).

I am trying to understand the impact of the duplicate CRIDs. So would the old CRID ever be returned by a CMR query? Would there be reprocessing that might update the `revision_date` for that granule CRID?

Maybe the best way to move forward is to define an environment variable (that we can easily change) for the current CRID and then perform a check on the CMR query results to remove any granules that do not have the current CRID. This way we won't even track the ingest of old CRIDs?

Or do we want to track the ingest of earlier CRIDs but specifically make sure we do not update current CRIDs with earlier CRIDs? If that is the case then we may be able to filter the Hydrocron SWOT table query using the current CRID so we don't do any overwriting of current data.

@torimcd - What do you think?

**Comment by torimcd** [comment]
Summarizing our discussion on this:
- Multiple CRIDs will be 'active' at one time - one for fwd stream, and one for reprocessing
- we do not expect to ingest **more** than 2 CRIDS at the same time for the same collection
- forward stream CRID will alway be archived first. 
- The input data between fwd and reproc are different. PIx0/forward is made with low-latency inputs: the medium-accuracy orbit ephemeris (MOE) and radiometer data (L2 RAD IGDR, "interim" geophysical data record). PGC0 is made with the best available inputs: the precise orbit ephermis (POE) and radiometer data (L2 RAD GDR)
- Hydrocron will **only** expose the latest product (reprocessed CRIDs) for time periods when both fwd and reproc CRIDs are available in the PODAAC archive
- for tracking/reconciliation, we will move to query the **parent** collection instead of the **child** collections for each feature type, and then filter the results per feature/CRID. This avoids any complication around delays in the reassociation process in the data archive
