### ISSUE TITLE
Enable notification of swot shapefile ingest to tva

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#70]
I&A update cumulus configurations to send CNM-R messages to TVA SNS Topic

I&A Requirements:

- ARN for SNS topic that CNM-R messages should be sent to

TVA Services requirements:

- Allow I&A permission to publish to SNS
- Use s3 credentials direct access to download file

TODO:
- Specific collection shortname/concept IDs

**Comment by torimcd** [comment]
Add SNS topic terraform, provide ARN to I&A

**Comment by torimcd** [comment]
set up SQS queue to receive SNS message and trigger lambda
