### ISSUE TITLE
Update log messaging format

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#75]
EDC Metrics will provide the messaging format we should use. Need to update code to use correct messaging format

**Comment by frankinspace** [comment]
Helpful wiki links:
[Cloud Metrics 101 for TRT](https://wiki.earthdata.nasa.gov/x/eILTEw)
[Data Schema Collaboration Space](https://wiki.earthdata.nasa.gov/x/g5TIDg)

**Comment by vggonzal** [comment]
Ticket created:
https://bugs.earthdata.nasa.gov/servicedesk/customer/portal/12/CMSD-13
