### ISSUE TITLE
Create UMM-S record for hydrocron

### ISSUE THREAD

**Issue by frankinspace** [podaac/hydrocron#77]
Hydrocron is a new service being offered and should have a UMM-S record created describing what the service is.

AC: 
- UMM-S JSON file created and checked in to repo
- Github workflow step added which updates UMM-S record as part of CICD

**Comment by nikki-t** [comment]
I fixed the URL and updated the GitHub Action workflow to include a "Publish" step which publishes the UMM-S record if the build and docker steps completed successfully. This will allow us to test publication of the record without deploying to any of the AWS environments. 

However, I ran into an issue when testing the GitHub Action. The log can be found [here](https://github.com/podaac/hydrocron/actions/runs/8055989675/job/22004216213). The `cmr-umm-updater` returns the following error message: `/entrypoint.sh: line 16: cmr/cmr.json: No such file or directory`

@frankinspace - do you know what might be causing this error? I believe that I have the `cmr` directory with the appropriate UMM-S JSON in the correct place.

**Comment by frankinspace** [comment]
@nikki-t it looks like in your action you are referring to the umm-json file as `cmr/hydrocron_umm_s.json` 

https://github.com/podaac/hydrocron/blob/313ddec82e7ac918a1df10d53e0142135a16b00b/.github/workflows/build.yml#L320

But the name of the file in the repo is actually `cmr/cmr.json`

https://github.com/podaac/hydrocron/blob/313ddec82e7ac918a1df10d53e0142135a16b00b/cmr/cmr.json


I would suggest renaming the file in the repo to `hydrocron_umm_s.json`

**Comment by nikki-t** [comment]
I figured out the error I was encountering but it looks like the `cmr-umm-updater` GitHub Action only works for `uat` and `ops` environments. 

```bash
 jq: error (at cmr/cmr.json:85): Cannot index string with string "URLValue"
INFO:root:Starting UMM-S update
INFO:root:native_id: POCLOUD_podaac_hydrocron
Traceback (most recent call last):
  File "/venv/bin/umms_updater", line 8, in <module>
    sys.exit(run())
  File "/venv/lib/python3.9/site-packages/podaac/umms_updater/umms_updater.py", line 298, in run
    main(_args)
  File "/venv/lib/python3.9/site-packages/podaac/umms_updater/umms_updater.py", line 218, in main
    concept_id = pull_concept_id(args.env, provider, native_id, args.timeout)
  File "/venv/lib/python3.9/site-packages/backoff/_sync.py", line 43, in retry
    ret = target(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/podaac/umms_updater/umms_updater.py", line 156, in pull_concept_id
    url_prefix = svc_update.cmr_environment_url(cmr_env)
  File "/venv/lib/python3.9/site-packages/podaac/umms_updater/util/svc_update.py", line 37, in cmr_environment_url
    raise Exception('CMR environment selection not recognized;'
Exception: CMR environment selection not recognized; Select uat or ops.
```

Does it make sense to hold off and only publish a UMM-S record for hydrocron UAT and OPS deployments? I can update the build.yml so that it is only triggered for those environments.

**Comment by frankinspace** [comment]
ah, yes that is correct. No umm-s in SIT
