### ISSUE TITLE
Add variable units to API response

### ISSUE THREAD

**Issue by torimcd** [podaac/hydrocron#85]
Data in the source shapefiles does not contain units. Units are critical for interpreting and analyzing the data. We can either:
- add units as constants in the code, to be appended as fields to the API response
- add units as additional fields to each dynamo db entry

Briefly discussed in App Sci meeting and thought adding in the code instead of the db would be preferred path

**Comment by torimcd** [comment]
Implement by adding units as items to each database record to keep code clean. Can read units from shp.xml sidecar file.

**Comment by nikki-t** [comment]
Going to start work on adding units to the API response.
