### ISSUE TITLE
Explore possibility of setting CORS headers

### ISSUE THREAD

**Issue by devincowan** [podaac/hydrocron#91]
I'm testing the beta 1.0 timeseries endpoint at https://soto.podaac.uat.earthdatacloud.nasa.gov/hydrocron/v1/timeseries.

I've noted that the `Access-Control-Allow-Origin` header is not set.
This limits the clients that can call the endpoint. Our use case is direct [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) calls that require CORS headers to be set from Hydrocron, for the responses to be usable.

Maybe explore adding that header? (perhaps along with `Vary: Origin` https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#cors_and_caching)

**Comment by frankinspace** [comment]
Thanks for the suggestion @devincowan. We had not considered CORS headers because the API is unauthenticated at this time. But I agree it would still be beneficial to do so. We will have to check if there are any limitations levied on us by NASA security but I believe we should be able to accommodate this.

**Comment by nikki-t** [comment]
I was able to define and test CORS headers for the API Gateway timeseries resource by following this [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/enable-cors-for-resource-using-swagger-importer-tool.html) to add it to the OpenAPI specification. The relevant code can be found [here](https://github.com/podaac/hydrocron/blob/007c6bdb71c86ea56a0d7edb02e0c3b0b9859a17/terraform/api-specification-templates/hydrocron_aws_api.yml#L167-L197).

Reading through this documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#the_http_response_headers, I don't think we need to add the `Vary: Origin` header as it seems to only be required if we specify a single origin.

The code is currently deployed to our internal SIT environment while we explore security limitations.

**Comment by devincowan** [comment]
That's great news @nikki-t, thank you for the update!

**Comment by devincowan** [comment]
@nikki-t no big deal but thought you'd like to know, when I run a [simple CORS test](https://cors-test.codehappy.dev/?url=https%3A%2F%2Fsoto.podaac.uat.earthdatacloud.nasa.gov%2Fhydrocron%2Fv1%2Ftimeseries%3Ffeature%3DReach%26feature_id%3D13330800375%26start_time%3D2024-01-01T00%253A00%253A00Z%26end_time%3D2024-10-30T00%253A00%253A00Z%26output%3Dgeojson%26fields%3Dtime_str%252Cwse%252Cslope%252Cgeometry&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get) I don't see a `Access-Control-Allow-Origin` header being set. Here are the ones I do see:

> cf-cache-status: DYNAMIC
cf-ray: 86f1e371d0056ac7-BOS
connection: keep-alive
content-type: application/json
date: Thu, 04 Apr 2024 14:11:36 GMT
server: cloudflare
strict-transport-security: max-age=31536000; includeSubDomains; preload
transfer-encoding: chunked
vary: Accept-Encoding
via: 1.1 100ce1d37f67e6c59753cd4c9c473afc.cloudfront.net (CloudFront)
x-amz-apigw-id: VtE7vEkUvHcEcQg=
x-amz-cf-id: vPzUqcZu3jqrJLU3dcGZp8n1eLyETremnNjGYQe5RQqvhIVa64hunA==
x-amz-cf-pop: JFK50-P7
x-amzn-remapped-connection: keep-alive
x-amzn-remapped-content-length: 61978
x-amzn-remapped-date: Thu, 04 Apr 2024 14:11:36 GMT
x-amzn-remapped-server: Server
x-amzn-remapped-x-amzn-requestid: bf30de5f-8b6b-4957-bb7a-4234c3d754df
x-amzn-remapped-x-forwarded-for: 2a06:98c0:3600::103, 172.68.54.77, 64.252.68.165
x-amzn-requestid: 3ae8b656-734a-4af9-b7c7-eff79046df6e
x-amzn-trace-id: Root=1-660eb517-7c9e6e331f67bb596c6988c3;Parent=51da97b5380c5bf4;Sampled=0;lineage=1f12e958:0
x-cache: Miss from cloudfront
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-request-id: vPzUqcZu3jqrJLU3dcGZp8n1eLyETremnNjGYQe5RQqvhIVa64hunA==
x-xss-protection: 1; mode=block

**Comment by frankinspace** [comment]
CORS enabled for GET requests. Fixed in https://github.com/podaac/hydrocron/releases/tag/1.1.0rc4
https://github.com/podaac/hydrocron/pull/156
