### ISSUE TITLE
Format the API gateway resource policy to match NGAP's policy

### ISSUE THREAD

**Issue by nikki-t** [podaac/hydrocron#95]
Working with NGAP support, it seems that we can format the API gateway resource policy to match the NGAP-defined policy and this will not trigger a replacement. This will allow us to make sure the deployed API stage is in sync with Terraform and not produce unexpected behavior preventing API access.

The resource policy includes many IP CIDR ranges, 2 VPC networks, and 1 VPC Endpoint. These values can be stored as GitHub Actions secrets and referenced by the Terraform code via variable to prevent sensitive data from being shared.

**Comment by frankinspace** [comment]
@nikki-t do you know if it is static for all environments or will it need to change based on environment? Or how often they update the policy on their side?

**Comment by nikki-t** [comment]
According to NGAP support, the resource policy should be fairly static where the CIDRs, VPCs and VPC endpoint shouldn't change. 

I am investigating whether these values change based on environment as well as if NGAP could host the resource policy as an IAM policy or store it in an SSM parameter that we can retrieve in our Terraform.

**Comment by nikki-t** [comment]
@frankinspace What do you think about using the Terraform meta-argument `ignore_changes` as documented [here](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes)? I could do some testing to see if this impacts the API stage deployment.

**Comment by frankinspace** [comment]
Yeah I think that could be a reasonable workaround as we continue to ask for support from platform
